<footer>
    <nav class="kvwap-nav">
        <ul class="kvwap-diaplay-box text-center p0">
            <li class="kvwap-box-flex"><a href="/" {if $c=='index'}class="on"{/if}><i class="kvwap-icon kvwap-icon-home iconfont">&#xf0011;</i>设备管理</a></li>
            <li class="kvwap-box-flex"><a href="?c=work" {if $c=='work'}class="on"{/if}><i class="kvwap-icon kvwap-icon-home iconfont">&#xe68e;</i>日常工作</a></li>
            <li class="kvwap-box-flex"><a href="?c=search" {if $c=='search'}class="on"{/if}><i class="kvwap-icon kvwap-icon-home iconfont">&#xe632;</i>资料查询</a></li>
            <li class="kvwap-box-flex"><a href="?c=article" {if $c=='article'}class="on"{/if}><i class="kvwap-icon kvwap-icon-home iconfont">&#xe618;</i>我的资料</a></li>
        </ul>
    </nav>
</footer>
</body>
</html>