<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>{$title}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link rel="stylesheet" href="{$skin}style/css/bootstrap.css">
    <link rel="stylesheet" href="{$skin}style/css/app.css">
    <link rel="stylesheet" href="{$skin}style/css/font.css">
    <script src="{$skin}style/js/jquery.min.js"></script>
    <script src="{$skin}style/js/bootstrap.min.js"></script>
</head>
<body>