{tpl head}

<header class="header-fix main-nav bg-black header header-lg navbar navbar-fixed-top-xs box-shadow">
  <div class="container">
    <div class="navbar-header aside-sm"> <a class="btn btn-link visible-xs" href="javascript:history.back()"> <i class="icon iconfont">&#xf007a;</i> </a>
      <div class="navbar-brand">详细信息 </div>
    </div>
  </div>
</header>
{$msg}
</body>
</html>
