<link rel="stylesheet" type="text/css" href="{$skin}css/bootstrap.min.css?12" />
<link rel="stylesheet" type="text/css" href="{$skin}css/basic.css?12" />
<link rel="stylesheet" type="text/css" href="{$skin}style/index.css?12" />
<script type="text/javascript" src="{$skin}js/jquery.min.js"></script>
<link rel="shortcut icon" type="image/png" href="{$skin}img/favicon.png" />
<script type="text/javascript" src="{$skin}js/bootstrap.min.js"></script>