<!DOCTYPE html>
<html lang="zh-cn">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=0" name="viewport"> 
<meta content="yes" name="apple-mobile-web-app-capable"> 
<meta content="yes" name="apple-touch-fullscreen">
<meta content="black" name="apple-mobile-web-app-status-bar-style">
<meta content="320" name="MobileOptimized">
<meta content="telephone=no" name="format-detection">
<link rel="stylesheet" href="{$skin}lp/qdwap.css">
<link href="{$skin}img/favicon.ico" type="image/x-icon" rel="icon">
<title>滴滴28 幸运28 PC蛋蛋 蛋蛋28 加拿大28 韩国28 北京28 北京赛车</title>
<meta name="keywords" content="幸运28 PC蛋蛋 蛋蛋28 加拿大28 韩国28 北京28 北京赛车">
<meta name="description" content="幸运28 PC蛋蛋 蛋蛋28 加拿大28 韩国28 北京28 北京赛车">
<style>
body{background: #856D35;}
#page{max-width:640px; }
header{background: #000000;}
</style>
</head>
 
<body>
<div id="page">

<header>
    <h1>滴滴网 幸运28 PC蛋蛋 蛋蛋28 加拿大28 韩国28 北京28 北京赛车</h1>
</header>

 
<div class="banner">
<p><a href="./index.php"><img src="{$skin}lp/bk.png"></a></p>
</div>

<section class="buy">    
<a class="btn" href="./index.php">进入体验</a>
</section>
     
<article class="showcontent">    

	<h2>滴滴28简介</h2>
	<div class="btn">
		<p><span style="font: 16px/24px Helvetica, Arial, san-serif; color: rgb(0, 0, 0); text-transform: none; text-indent: 0px; letter-spacing: normal; word-spacing: 0px; float: none; display: inline !important; white-space: normal; font-size-adjust: none; font-stretch: normal; background-color: rgb(249, 249, 249); -webkit-text-stroke-width: 0px;"></span></p>
		<p style="margin-top: 0px; margin-bottom: 0px; white-space: normal; box-sizing: border-box; font-family: 微软雅黑; line-height: 24px; background-color: rgb(249, 249, 249);">
			<span style="margin: 0px; box-sizing: border-box; background-color: rgb(255, 255, 255);">
				<strong style="margin: 0px; box-sizing: border-box;">滴滴28是一家以各大官方开奖为依据的28游戏平台  官方开奖 绝对 公平 公正 公开，</strong>
				<strong style="margin: 0px; box-sizing: border-box;">依靠最雄厚的财团实力 最诚信的经验理念 最优质的服务态度   最快的上分出款速度   最可信的技术团队  缔造28游戏的传奇品牌。</strong>
				
			</span>
		</p>
		<p></p>
	</div>
	<br>
	<br>


	<h2>App下载</h2>
	<div class="btn">
		<p></p>
		<p style="text-align:center;">
		  	<div style="text-align:center;font-size:22px;padding-top:50px;">
		        <a href="itms-services://?action=download-manifest&url=https://vip.didi8888.com/download/kdy28.plist"><img src="{$skin}lp/download-ios.jpg" /></a>
		  	</div>
		  	
		  	<div style="text-align:center;font-size:22px;padding-top:120px;padding-bottom:50px;">
		        <a id="andrioddownload" href="https://vip.didi8888.com/download/kdy28.apk"><img src="{$skin}lp/download-andriod.jpg" /></a>
		  	</div>
		</p>
		<p></p>
	</div>
	
	<!--  
	<h2>购买流程</h2>
	<p><img src="{$skin}lp/bk.png"></p>
	-->
	
	<br>
	<br>
	 
	<h2>客户服务</h2>
	<div class="btn">
		<p><span style="font: 16px/24px Helvetica, Arial, san-serif; color: rgb(0, 0, 0); text-transform: none; text-indent: 0px; letter-spacing: normal; word-spacing: 0px; float: none; display: inline !important; white-space: normal; font-size-adjust: none; font-stretch: normal; background-color: rgb(249, 249, 249); -webkit-text-stroke-width: 0px;"></span></p>
		<p style="margin-top: 0px; margin-bottom: 0px; white-space: normal; box-sizing: border-box; font-family: 微软雅黑; line-height: 24px; background-color: rgb(249, 249, 249);">
			<span style="margin: 0px; box-sizing: border-box; background-color: rgb(255, 255, 0);">
				<strong style="margin: 0px; box-sizing: border-box;">1、QQ客服在线</strong>
				<strong style="margin: 0px; box-sizing: border-box;">：</strong>
				<strong style="margin: 0px; box-sizing: border-box;"></strong>
				<strong style="margin: 0px; box-sizing: border-box;"></strong>
				<strong style="margin: 0px; box-sizing: border-box;"></strong>
				<span style="margin: 0px; box-sizing: border-box; color: rgb(255, 0, 0);">
					<strong style="margin: 0px; box-sizing: border-box;">
	                <a href="{$qqurl}">78271214</a>
					</strong>
				</span>
			</span>
		</p>
		<p style="margin-top: 0px; margin-bottom: 0px; white-space: normal; box-sizing: border-box; font-family: 微软雅黑; line-height: 24px; background-color: rgb(249, 249, 249);">
			<span style="margin: 0px; box-sizing: border-box; background-color: rgb(255, 255, 0);">
				<strong style="margin: 0px; box-sizing: border-box;">2、玩家QQ群</strong>
				<strong style="margin: 0px; box-sizing: border-box;">：</strong>
				<strong style="margin: 0px; box-sizing: border-box;"></strong>
				<strong style="margin: 0px; box-sizing: border-box;"></strong>
				<strong style="margin: 0px; box-sizing: border-box;"></strong>
				<span style="margin: 0px; box-sizing: border-box; color: rgb(255, 0, 0);">
					<strong style="margin: 0px; box-sizing: border-box;">635498265</strong>
				</span>
			</span>
		</p>
		<p></p>
	</div>
</article>  


         

<footer>
	<p></p><center><img src="{$skin}lp/foot.png"></center><p></p>
</footer>

</div>

<!-- 
<nav>
  <ul class="Transverse">
     <li><a href="#"><strong>进入手机版</strong></a></li> 
	 <li><a href="tel:15200000000"><strong>电话咨询</strong></a></li>  
  	 <li><a href="sms:15200000000"><strong>短信订购</strong></a></li>
  </ul>
</nav>
-->

<div style="display: none">
<script type="text/javascript">var cnzz_protocol = (("https:" == document.location.protocol) ? " https://" : " http://");document.write(unescape("%3Cspan id='cnzz_stat_icon_1261271146'%3E%3C/span%3E%3Cscript src='" + cnzz_protocol + "s4.cnzz.com/z_stat.php%3Fid%3D1261271146' type='text/javascript'%3E%3C/script%3E"));</script>          
</div>

</body>
</html>
