<!DOCTYPE html>
<html lang="zh-cn">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=0" name="viewport"> 
<meta content="yes" name="apple-mobile-web-app-capable"> 
<meta content="yes" name="apple-touch-fullscreen">
<meta content="black" name="apple-mobile-web-app-status-bar-style">
<meta content="320" name="MobileOptimized">
<meta content="telephone=no" name="format-detection">
<link rel="stylesheet" href="{$skin}lp/qdwap.css">
<link href="{$skin}img/favicon.ico" type="image/x-icon" rel="icon">
<title>滴滴28 幸运28 PC蛋蛋 蛋蛋28 加拿大28 韩国28 北京28 北京赛车</title>
<meta name="keywords" content="滴滴28 幸运28 PC蛋蛋 蛋蛋28 加拿大28 韩国28 北京28 北京赛车">
<meta name="description" content="滴滴28 幸运28 PC蛋蛋 蛋蛋28 加拿大28 韩国28 北京28 北京赛车">
<style>
body{background: #856D35;}
#page{max-width:640px; }
header{background: #000000;}
</style>
</head>
 
<body>
<div id="page">

<article class="showcontent"> 
	<div><img src="{$skin}lp/bk5.png" usemap="#imgMap"></div>
	
	<map name="imgMap" id="imgMap">
		<area id= "area1" shape="rect" coords="7,60,286,104" href ="./index.php" />
		<area id= "area2" shape="rect" coords="29,798,186,862" href ="itms-services://?action=download-manifest&url=https://vip.didi8888.com/download/kdy28.plist" />
		<area id= "area3" shape="rect" coords="29,899,186,963" href ="https://vip.didi8888.com/download/kdy28.apk" />
		<area id= "area4" shape="rect" coords="313,803,622,869" href ="{$qqurl}" />
	</map>
	<script type="text/javascript" src="js/jquery-1.7.2.min.js" ></script>
	<script>
    //重新定位map位置
    function rsz(){
        //正常情况下为640尺寸:计算比例
        var bl=$("body").innerWidth()/640;
        var x1=bl*7;
        var y1=bl*60;
        var x2=bl*286;
        var y2=bl*104;

        var x3=bl*29;
        var y3=bl*798;
        var x4=bl*186;
        var y4=bl*862;

        var x5=bl*29;
        var y5=bl*899;
        var x6=bl*186;
        var y6=bl*963;

        var x7=bl*313;
        var y7=bl*803;
        var x8=bl*622;
        var y8=bl*869;
        
        //重新计算位置
        $("#area1").attr({"coords":x1+","+y1+","+x2+","+y2});
        $("#area2").attr({"coords":x3+","+y3+","+x4+","+y4});
        $("#area3").attr({"coords":x5+","+y5+","+x6+","+y6});
        $("#area4").attr({"coords":x7+","+y7+","+x8+","+y8});
    }
    
    //窗口宽度改变时执行
    $(window).resize(function() {
        rsz();
    });
    
    //页面初始化时候执行
    $(function(){
        rsz();
    })
	</script>
</article> 

<footer>
	<p></p><center><img src="{$skin}lp/foot.png"></center><p></p>
</footer>

</div>


<div style="display: none">
<script type="text/javascript">var cnzz_protocol = (("https:" == document.location.protocol) ? " https://" : " http://");document.write(unescape("%3Cspan id='cnzz_stat_icon_1261271146'%3E%3C/span%3E%3Cscript src='" + cnzz_protocol + "s4.cnzz.com/z_stat.php%3Fid%3D1261271146' type='text/javascript'%3E%3C/script%3E"));</script>          
</div>

</body>
</html>
